title: North American Motorsports Research
short_title: NAMR
description: Pioneering free and open performance tuning for modern vehicles.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false

url: "https://motorsportsresearch.org" 
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
theme: 
socials:
  instagram: namotorsportsresearch
  discord: tbWJshQvqR
  youtube: NAMR-Atlas
  patreon: NAMR
#  facebook:
square: 
  donations: true
  embed: kE9E7DmT
  link: kE9E7DmT
links:
  atlasdocs: https://docs.motorsportsresearch.org/books/atlas-documentation
plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-seo-tag
target-blank:
    rel: nofollow
    noopener: true
    noreferrer: true
header_page_refs: ['shop', 'download', 'docs', 'support', 'faq', 'emissions', 'news', 'discord']
defaults:
  - scope:
      path: ""
    values:
      image: /assets/opengraph.jpg
